-- Abuse reports against short links. There is one row per link and reporter: a reporter who reports the same
-- link again refreshes their row, so every reporter counts once towards an automatic takedown. reporter_hash
-- is a keyed pseudonym of the reporter's network, scoped to the link (see ReporterFingerprint); the client
-- address itself is never stored.
CREATE TABLE abuse_report (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id       BIGINT                   NOT NULL,
    reporter_hash CHAR(64)                 NOT NULL,
    reason        VARCHAR(16)              NOT NULL,
    reported_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_abuse_report_short_link FOREIGN KEY (link_id) REFERENCES short_link (id),
    -- Its index also serves the per-link takedown count. No separate (link_id, reported_at) index: a link
    -- rarely collects more rows than the takedown threshold, because reports stop once it is disabled.
    CONSTRAINT uk_abuse_report_link_id_reporter_hash UNIQUE (link_id, reporter_hash)
);
