CREATE TABLE short_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(32)              NOT NULL,
    target_url      VARCHAR(2048)            NOT NULL,
    status          VARCHAR(16)              NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    disabled_at     TIMESTAMP WITH TIME ZONE NULL,
    idempotency_key VARCHAR(64)              NULL,
    request_hash    CHAR(64)                 NULL,
    CONSTRAINT uk_short_link_code UNIQUE (code),
    CONSTRAINT uk_short_link_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE click_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id       BIGINT                   NOT NULL,
    occurred_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    referrer_host VARCHAR(255)             NULL,
    CONSTRAINT fk_click_event_short_link FOREIGN KEY (link_id) REFERENCES short_link (id)
);

CREATE INDEX ix_click_event_link_id_occurred_at ON click_event (link_id, occurred_at);
